name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install mobile dependencies
      working-directory: ./mobile
      run: npm install

    - name: Make Gradlew executable
      working-directory: ./mobile/android
      run: chmod +x ./gradlew

    - name: Build Android APK
      working-directory: ./mobile/android
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beepstream-android-apk
        path: mobile/android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: BeepStream Mobile v${{ github.run_number }}
        body: |
          Automated build of BeepStream mobile app.
          
          ## Installation Instructions
          1. Download the APK file below
          2. Enable "Unknown sources" in Android settings
          3. Install the APK on your phone
          
          ## Features
          - Real-time log monitoring
          - Background notifications
          - Audio alerts for critical logs
          - Kill switch functionality
          - Daily archival integration
        files: mobile/android/app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false